wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/base_codec_1.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/base_codec_2.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/base_codec_3.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/base_codec_4.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/cls_1.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/cls_2.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/cls_3.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/cls_4.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/det_1.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/det_2.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/det_3.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/det_4.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/seg_1.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/seg_2.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/seg_3.pth.tar
wget -P examples/utils https://github.com/NYCU-MAPL/TransTIC/releases/download/v1.0/seg_4.pth.tar